### ISSUE TITLE
#update tags

### ISSUE THREAD

**Issue by ashokrags** [compbiocore/dockerfiles#1]
Please update the tags`v1` to `gcc_4_8_5` and `v2` to `gcc_5_4_0`

**Comment by andrew-leith** [comment]
Are these both on compbiocore Anaconda?

**Comment by andrew-leith** [comment]
All I see on anaconda/compbiocore is gcc_5_4_0, where should I source gcc_4_8_5 from?

**Comment by andrew-leith** [comment]
v2 is being updated now; v1 will be handled separately later

**Comment by andrew-leith** [comment]
Resolved.
